<html>
<head><title>Exercise 1</title></head>
<body bgcolor = "Blue" >
<?php

    $FullName = "Jhad Aldrich S. Domingo";
    echo $FullName;
    echo "<br>";
    $CollegeProgram = "BS Computer Engineering";
    echo $CollegeProgram;
    echo "<br>";
    $YearandSection = "3rd Year - 58043";
    echo $YearandSection;
    echo "<br>";
    echo $string = "Today, I will learn PHP Programming";

?>

</body>
</html>
You sent
tapos mo na?
